version: '3'

services:
    python:
        image: python:3.9
        volumes:
            - ./django_tea_do:/django_tea_do
        ports:
            - 8000:8000
        command: bash -c "cd ./django_tea_do && pip install -r requirements.txt&& python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
