# Generated by Django 4.0.2 on 2022-02-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_do', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teado',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teado',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
