# Generated by Django 4.0.2 on 2022-02-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_do', '0002_alter_teado_body_alter_teado_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teado',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
