# Generated by Django 4.0.2 on 2022-02-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_do', '0003_alter_teado_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teado',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teado',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
